### PR TITLE
fix broken link to AUR package

### PR DESCRIPTION
**Pull request by wfriesen**

### CODE REVIEW

**Comment by SanskritFritz** [comment]
Well, to be more precise, kupfer is available in the official community repository:
https://www.archlinux.org/packages/community/any/kupfer/

**Comment by bluss** [comment]
@SanskritFritz cool. Can you merge in this or any PR that has the correct URL? Thanks

**Comment by SanskritFritz** [comment]
@bluss Hey man, you're still here, good 😄 
Yes, I'll do it, or just fix it myself. But how will the changes be propagated to the website?

**Comment by bluss** [comment]
This is a github pages repo, they should update there automatically. Usually takes less than 5 mins.

**Comment by SanskritFritz** [comment]
I could have thought of this. Ok, I'll just fix this soon.

**Comment by SanskritFritz** [comment]
@wfriesen Thanks for the heads-up!

**Pull request closed without merging**
